theme: Solarized (dark)

font_family: Source Han Code JP R

font_size: 12

# tab_width: 4

# indent_using_spaces: false

# end_of_line_str:
#   str: '←'
#   color: '#0000ff'

# end_of_file_str:
#   str: '[EOF]'
#   color: '#ff0000'

# enable_mnemonic: false